In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
import numpy as np

In [ ]:
l = [1, 2,3 ,4 ,5 ,6 ]

In [ ]:
arr = np.array(l)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
np.array()

array([1, 2, 4])

In [ ]:
l2d = [[1, 2,3], [4, 5, 6], [7, 8, 9]]

In [ ]:
arr2d = np.array(l2d)

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2d.shape

(3, 3)

In [ ]:
np.arange(10, 20,  2)

array([10, 12, 14, 16, 18])

In [ ]:
np.zeros((4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
x = np.ones((5,  4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
x[3][2]

1.0

In [ ]:
x[3, 2] = 99

In [ ]:
x

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1., 99.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [ ]:
np.ones((5,  4))*2+7 #Each value is multiplied by 2 and 

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [6]:
x = np.ones((3, 4, 5))
x

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [ ]:
x.shape

(3, 4, 5)

In [ ]:
x.reshape((5, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
x.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
x = np.eye(6)
x

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [3]:
y = np.ones((6,6))

NameError: ignored

In [ ]:
y == x

array([[ True, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False,  True, False],
       [False, False, False, False, False,  True]])

In [ ]:
y = y*3

In [ ]:
y.dot(x)

array([[3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3.]])

In [ ]:
np.cross(x, y)

ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [ ]:
x.shape

(6, 6)

In [ ]:
y.shape

(6, 6)

In [ ]:
x = np.arange(30)

In [ ]:
x = x.reshape((5, 6))

In [ ]:
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
x.mean()

14.5

In [ ]:
sum(sum(x))/30

14.5

In [ ]:
x.std()

8.65544144839919

In [ ]:
x.mean(axis = 0) # columns wise

array([12., 13., 14., 15., 16., 17.])

In [ ]:
x.std(axis = 1)

array([1.70782513, 1.70782513, 1.70782513, 1.70782513, 1.70782513])

In [ ]:
x.mean(axis =1)

array([ 2.5,  8.5, 14.5, 20.5, 26.5])

In [ ]:
np.log(x)

C:\Users\Akash\Anaconda3\envs\rootenv\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
        1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
        2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 , 2.77258872,
        2.83321334],
       [2.89037176, 2.94443898, 2.99573227, 3.04452244, 3.09104245,
        3.13549422],
       [3.17805383, 3.21887582, 3.25809654, 3.29583687, 3.33220451,
        3.36729583]])

In [ ]:
import math

In [ ]:
math.log(144, 12)

2.0

In [ ]:
np.random.rand(10)*5+5

array([5.59014539, 6.14940154, 6.55864334, 9.0883563 , 7.39367509,
       7.92325254, 9.90529217, 6.73367984, 8.05571299, 5.05926377])

In [9]:
np.random.seed(20)
np.random.randint(1, 100, (3, 4))

array([[91, 16, 96, 29],
       [91, 10, 21, 76],
       [23, 72, 35, 97]])

In [ ]:
np.random.randint(1, 100, (3, 4))

array([[41, 86, 91, 27],
       [84, 17, 63, 17],
       [ 8, 99,  7, 27]])

In [ ]:
arr = np.arange(18)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
np.random.shuffle(arr)

In [ ]:
arr

array([ 8,  4,  1,  5,  7,  6, 12,  2,  0, 14, 17, 16, 15,  3,  9, 10, 11,
       13])

In [ ]:
arr.min()

0

In [ ]:
arr.max()

17

In [ ]:
arr.argmin()

8

In [ ]:
arr.argmax()

10

In [ ]:
arr.sort()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
np.linspace(0,  10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])